### ISSUE TITLE
Expose option to send worker ID to survey

### ISSUE THREAD

**Issue by AdamDarlow** [gideongoldin/TurkGate#77]

**Comment by jeffzemla** [comment]
Option to pass worker id to the survey had been coded into gateway.php but required manually setting a PHP flag. @markkho and I did not realize this and re-implemented it in webTemplate.html and exposed the option on the main page.

I deleted the duplicate code from gateway.php to avoid future confusion, but kept @dhagmann 's commit which passed assignmentId to the survey. As a result, TurkGate will now *always* send assignment id to the survey. I don't see this as problematic, as the survey will just ignore this GET parameter unless the user does something with it. If I overlooked something, please revert.
